### PR TITLE
Successive improvements

### PR DESCRIPTION
**Pull request by Philonous**
Stringprep became a bottleneck for validating JIDs for QuickCheck-testing of pontarius-xmpp, so I harvested some low-hanging fruit. Specifically, profiling showed that merging ranges in the range package accounted for most of the run time, so I exchanged the O(n^2) merging algorithm for a O(n*log n) one. Since you deprecated ranges I also folded the relevant code into stringprep and specialized it to chars. I added a test to check that the new code and the old one behave the same. 
Overall this yielded a 50-fold increase in speed for validating my test JID.

### CODE REVIEW

**Comment by Porges** [comment]
Thanks, this puts together some work I had wanted to do for a while.

Did you consider any other approaches to the ranges replacements? I had thought that using something like attoparsec's Data.Attoparsec.FastSet would also improve the performance drastically, but I didn't really want to pull in a dep on it.

**Comment by Philonous** [comment]
I've tried a few data structures and got the following results: 
https://rawgithub.com/Philonous/stringprep-hs/bench/bench.html
Times are for 1 set creation and 100 lookups each

"Ranges with improved toSet" is the original (polymorphic) ranges but with the toSet algorith replaced
https://github.com/Philonous/stringprep-hs/blob/bench/bench/Ranges.hs
"CharRanges" is ranges but specialized to (unboxed) Chars
https://github.com/Philonous/stringprep-hs/blob/bench/Text/CharRanges.hs
"Ranges Hash" is the same as CharRanges but with Set replaced by HashSet (from unordered-containers)
https://github.com/Philonous/stringprep-hs/blob/bench/bench/CharRangesAlt.hs
"Fast Range Set" is a custom data structure (explained below)
https://github.com/Philonous/stringprep-hs/blob/bench/bench/Text/FastRangeSet.hs

I tried dumping all the characters (some 130k) from the nameprep prohibited ranges into a attoparsec FastSet. Unsurprisingly, the result was completely unsatisfactory. So I changed FastSet to store pairs of chars (the bounds of the original ranges) and adapted the binary search algorithm.  The result is much more reasonable but does't perform better than the alternatives.

**Comment by Porges** [comment]
Great!

There's a few cabal cleanup things I'll need to do before pushing the new version to hackage, will try to get these done this evening.

**Comment by Porges** [comment]
This is (finally!) released as stringprep-1.0.0 on Hackage.

**Pull request merged**
